{
 "title": "Home",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Response time quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (quantile) (finances_bot_summary_response_time_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(\n    rate(finances_bot_summary_response_time_seconds_count[1m]) * 60\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Distribution of commands per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(\n    rate(finances_bot_summary_response_time_seconds_count[1m]) * 60\n) by (command)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution of response time among commands",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(\n    rate(finances_bot_summary_response_time_seconds_sum[1m]) * 60\n) by (command)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}