version: '3.9'
services:
  db:
    image: postgres:14-alpine
    container_name: finances-bot-db
    restart: always
    ports:
      - '9432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example

  cache:
    image: redis:7.0.5
    container_name: finances-bot-cache
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data


volumes:
  db-data:
  cache:
